# This file lists the most common parameters that you might want to use in a
# configuration file for use with the corr2 program.  (And eventually the 
# other corr varieties...)  See the wiki page:
#
# https://github.com/rmjarvis/TreeCorr/wiki/Configuration-Parameters
#
# for complete documentation about all the possible parameters you can use.
#
# The normal usage is:
#
# corr2 config.yaml
#
# You can also specify parameters on the command line after the name of 
# the configuration file. e.g.:
#
# corr2 config.yaml file_name=file1.dat ee_file_name=file1.out
# corr2 config.yaml file_name=file2.dat ee_file_name=file2.out
# ...
#
# This can be useful when running the program from a script for lots of input files.


####
#### Parameters about the input file
####


ra_units: degrees
dec_units: degrees


# For FITS files, the columns are specified by name, not number:
ra_col: alpha
dec_col: delta
g1_col: e1
g2_col: e2
#w_col: WEIGHT



# Sometimes there are issues with the sign conventions of gamma.  If you need to flip 
# the sign of g1 or g2, you may do that with flip_g1 or flip_g2 (or both).
flip_g1: false
flip_g2: false



####
#### Parameters about the binned correlation function to be calculated
####

# The bins for the histogram may be defined by setting 3 of the following 
# 4 parameters:
#     min_sep  = the left edge of the first bin
#     max_sep  = the right edge of the last bin
#     nbins    = the number of bins
#     bin_size = the width of the bins in log(sep)
min_sep: 1.
max_sep: 300.
bin_size: 0.10

# sep_units specifies the units to use for min_sep and max_sep.
# It is also the units of R in the output file.
# If omitted, radians is assumed.  (So when using x,y, you can just omit both
# this and x_units,y_units, and the units will match up and can be arbitrary.)
sep_units: arcmin


####
#### Parameters about the output files
####

# The kind of correlation function that the code will calculate is based on which
# output file(s) you specify.  It will do the calculation(s) relevant for each
# output file you set.

# For shear-shear correlations, the output file name is given by gg_file_name.


# The code can compute the mass aperture statistic from the two-point shear correlation 
# function if you specify m2_file_name.
#m2_file_name: m2.out

# For count-shear correlations, the output file name is given by ng_file_name.
#ng_file_name: ng.out

# For count-count correlations, the output file name is given by nn_file_name.
#nn_file_name: nn.out


####
#### Miscellaneous parameters
####

# verbose specifies how much progress output the code should emit.
# 0 = no output unless there is an error
# 1 = warnings (This is the default if not specified)
# 2 = progress information
# 3 = extra debugging output
verbose: 2

# num_threads = the number of threads to use.
# The default is to let OpenMP determine an appropriate number of threads automatically.
# Usually this matches the number of cores your system has.
#num_threads: 1

